components:
  schemas:
    HealthCheckResponse:
      properties:
        message:
          type: string
      type: object
paths:
  /:
    connect:
      responses: null
    delete:
      responses: null
    get:
      operationId: /-GET
      responses: {}
    head:
      responses: null
    options:
      responses: null
    patch:
      responses: null
    post:
      responses: null
    put:
      responses: null
    trace:
      responses: null
