name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: gofmt
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: lint
        run: golint $(go list ./... | grep -v /vendor/)

      - name: vet
        run: go vet $(go list ./... | grep -v /vendor/)
          
          